#!/bin/bash 
if [ "$1" = "-g" ] ; then
   mount --rbind /dev /VM/"$2"/rootfs/dev
   mount --make-rslave /VM/"$2"/rootfs/dev
   mount -t proc /proc /VM/"$2"/rootfs/proc
   mount --rbind /sys /VM/"$2"/rootfs/sys
   mount --make-rslave /VM/"$2"/rootfs/sys
   mount --rbind /tmp /VM/"$2"/rootfs/tmp
   mount --rbind /run /VM/"$2"/rootfs/run
   mount --make-rslave /VM/"$2"/rootfs/run
   Xephyr  "$3" -fullscreen &
   export DISPLAY="$3"
   echo '#!/bin/sh' >/VM/"$2"/rootfs/ginit
   echo 'unset DBUS_SESSION_BUS_ADDRESS' >> /VM/"$2"/rootfs/ginit
   echo 'unset SESSION_MANAGER' >> /VM/"$2"/rootfs/ginit
   echo export DISPLAY="$3" >> /VM/"$2"/rootfs/ginit
   chmod +x /VM/"$2"/rootfs/etc/X11/xinit/xinitrc
   echo 'exec /etc/X11/xinit/xinitrc' >> /VM/"$2"/rootfs/ginit
   chmod +x /VM/"$2"/rootfs/ginit
   chroot /VM/"$2"/rootfs /ginit &
   chroot  /VM/"$2"/rootfs
   exit
fi
if [ "$1" = "-s" ] ; then
   mount --rbind /dev /VM/"$2"/rootfs/dev
   mount --make-rslave /VM/"$2"/rootfs/dev
   mount -t proc /proc /VM/"$2"/rootfs/proc
   mount --rbind /sys /VM/"$2"/rootfs/sys
   mount --make-rslave /VM/"$2"/rootfs/sys
   mount --rbind /tmp /VM/"$2"/rootfs/tmp
   mount --rbind /run /VM/"$2"/rootfs/run
   mount --make-rslave /VM/"$2"/rootfs/run  
   chroot /VM/"$2"/rootfs || chroot /VM/"$2"/rootfs /bin/sh
   exit
fi
if [ "$1" = "-l" ] ; then
   ls /VM
   exit
fi
if [ "$1" = "-c" ] ; then
   mkdir /VM/"$2"
   mkdir /VM/"$2"/rootfs
   exit
fi
if [ "$1" = "-clean" ] ; then
   rm /VM/"$2"/boot/* /VM/"$2"/lib/modules/*
   exit
fi
if [ "$1" = "--guide" ] ; then
   cat <<EOF
To use svm, you need to use 'su'  to gain root permission.Please note that sudo may let this program cash.
Create a VM
      svm -c [your-vm-name] 
GestOS Installion
      Please note that svm does not support a normal installion of Guest OS.If you want to install a system from  LiveCD, just unpack it to /VM/your-vm-name/rootfs.You can also use kvm to install the system to a img file , then mount it on /VM/your-vm-name/rootfs or copy the guest os there.
Start a VM 
     svm -s [your-vm-name] 
Start a VM with GUI
    if you want start a VM with GUI,Xephyr is needed. Use 'svm [-g your-vm-name]  [Display Number]' to start .
    example:
    svm -g Debian :4
    Please make sure that display number is not occupied.
    You may neeed to edit the guests os's /etc/X11/xinit/xinitrc manually if the Desktop Environment failed to start.
Remove a VM
    rm /VM/your-vm-name
Remove Kernels in guest OS
     kernel in guest OS is not needed because all guest OS share the host's kernel 
     Use 'svm --clean [your-vm-name] to clean them'
EOF
exit
fi
cat <<EOF
Useage: svm [OPTION] [VMname] 
     
       -c Create a VM
       -s Start a VM
       -g Start a VM with GUI
       -l List all VMs
       
use "--guide" option to read the user guide
EOF
